name="Tejash !! Patel"
print(len(name))
print(name.upper())
print(name.lower())
print(name.rstrip("!"))
print(name.replace("Tejash","Patel"))
print(name.split(" "))
print(name.capitalize())
print(name.center(50))
print(name.count("Tejash"))
print(name.endswith("l"))
print(name.find("s"))
print(name.isalnum())
print(name.isalpha())
print(name.islower())
print(name.isprintable())
print(name.isspace())
print(name.istitle())
print(name.startswith("Tejash"))
print(name.swapcase())
print(name.title())